name: CasterOS
main: com.casteros.paper.CasterOSPaperPlugin
version: 1.0.0
api-version: 1.21
website: https://github.com/dgaberstein/CasterOS
authors: ["Daniel Gaberstein"]
description: Cross-platform magic system for Paper/Folia.
commands:
  casteros:
    description: Main command for CasterOS plugin. Use /casteros reload to reload spells.
    usage: |
      /casteros - Show plugin info
    aliases: []
